version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  playwright:
    build:
      context: ./playwright
      dockerfile: Dockerfile
    depends_on:
      frontend:
        condition: service_healthy
    volumes:
      - ./playwright:/app
      - /app/node_modules
    environment:
      - PLAYWRIGHT_BASE_URL=http://frontend:8080
